# Generated by Django 4.1 on 2022-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_user'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='bottles', to='clients.order', verbose_name='Заказы'),
        ),
    ]
